travis:
  secure:
    BINSTAR_TOKEN: mwYqMB5QloY8j07LBJvwC6uF0MjVsErcg96rsMIM6M9LsGw69lR/wWGn7hnfcNhiNd2VbNTwBmKOmpB1ovT6lJutl9jyqfaeg5gGMzME8cpFBIFnFpjbIf0XFGgu3fVelgZaaIs+G7C8cCHt29qIkzHmruOEEUWD+4bOMC48F+SPX9+OBMNyXQv3AgLR/HaTfRtflARdKUaRb8orSoz8EUK/bu61PCaGPQhr1jWoiaztnTByWcU2EJUOAkEFsfjkcYRl0P6aeLO56Rcx0WxMq8XIQuoYE/Y4Ct64hPaQEtm4Uo77gDMru5GfNEJJXbu0N0035cE8ab7DR+74fqkSXBPXeag2u+gIgSCu4uvZDuhD1nkUlWXGH3gLh8tT4lY8Q5z+s9s/mCXik04JDKXSqmpYiWTkH3tB1M4qz2TuWkd3+c4DG6iWXNB6T6lj9ft6jiFWirOrcXT/hBDxos398/zml2KBzYjYDswHcc0BU1CkXHEbPE70bEosvY6f/iRfuyGHpZfzOBGdWRRunDN0pPhBA3YPddN0dOha8dpXRLyG+vcpMF5ckNTbkeakHAsnwe9ZM4ndoUWQ5TW9sKrNu7Qa/qqzzYEb3EamcbIC6/TOImp5cIfHknmiYlCMPrLQPdWvTpUuUnPY0oPP7gvE4oXa0zvjT5vr5HWXlgWU8VY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
