travis:
  secure:
    BINSTAR_TOKEN: IahSprtTZ207rHR1nqF1lKXlPV6gtRqV6N/aU0kJlGrOfG33384Mj5ZIQvmv2BYHbuYfARcdzF013ekzz9MuMXGR56CkSzi+epo6b1Ih3tOe7rF+4UN89CYmp7PKYWPuBjSwB7sbqiZRWr8COdAWMAm5dfNYdbyOhXG6a+jUQOI9RhjesgdNZZ1nBkoIfLuYmsNbxbLBucTF2KT9pr12nTHk+qr0VyhdHCvxPQ4FfnDqJs3Ch8udovGxoI6QWSaMWarOWkQa+VDuZ3B2Bm88tL6OJB/Ii6abZtB65KvbIDBI1goosO4e6Lfpr4QhmwaTgFcxO8kZYgO3gA/YQ0njUtdHJUbRvkzFai/PgZ4Gzu/NiUiEsDdYEg+2hoIHKRkinA+092aqLlPxGzDDfBQ8U9jeeCFsTZgBURNwxJEOfXLmf0dx8rLWdY0jvzo9LEydLd6ejyBY6S84HC8AwxSQpfUC9QbsvcOERo0gl0xAgSJujsMWQK+TgQrZTedYZxqle7jYy3j1jtX/qlphxMjH7ZHWuN1EwINp25TjmJUSk4+w0PhQayPbHCuvvgvUhpWC/Ew+zQHR7vRDc/dJszP965xYzvcMT1xilPR8Aw/TR0Q5Ggow2Dt4GiQ3RM7Z1qIrH8S+l7/N3CEcr3mdG4Hmruj+uuFQ85foqi8/vKKpeEs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
